name: Build and Release

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux Package
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Wails CLI
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev upx

      - name: Build and package
        run: |
          chmod +x ./buildScript/buildDeb.sh
          ./buildScript/buildDeb.sh

      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: codezone-linux-deb
          path: codezone_*.deb
